Story1
cattre/portfolio pull request #1
Opened 2020-09-08 15:27 UTC by cattre

2020-09-09 08:41 UTC, ashleycoles requested changes
Really great work Rich! A few comments on here for you, mostly minor.

One extra thing, the images you're using for the slider are quite large in terms of file size. I'd suggest running them through an image optimiser like tinyjpg to reduce the file size. It shouldn't have an impact on image quality but should make the page load faster once it's out there on the web.

Would also suggest trying to see if you can get the video any smaller. Because it's quite large it will take a while to load, and also means that cloning/pulling/pushing in git might be a bit on the slow side.

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +		<link rel='stylesheet' type= 'text/css' href='portfolio.css'>
Use either all single or double quotes, consistency is key!

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +		<title></title>
Empty title element

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +					<img class='carouselimage' src='media/carousel7.jpg'>
All images should have an alt attribute (it should just describe what the image is)

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    margin-top: 0px;
I don't think any of these rules are having an effect

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +{
curly brace should be on the line before

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    clear: both;
These rules don't appear to do anything

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +}
Cool use of :target! Traditionally this is something that would be built using JavaScript, but this seems to work quite nicely. Well done!

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +						<img src='media/linkedin.png'>
Missing alt text

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +						<img src='media/github.png'>
missing alt text

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +						<img src='media/sendmail.png'>
missing alt text

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +						<img src='media/phone.png'>
Missing alt

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +		</section>
What will these look like once populated? Might be worth mocking one up with fake project details

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    letter-spacing: .6px;
Watch your indenting here

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    position: static;
Why static?

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    position: static;
(it's the default)

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +	outline: none;
Does this do anything?

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +	overflow: hidden;
This content should never overflow (i don't think), so shouldn't need this

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +}
Might as well combine these two into one

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    display: block;
Shouldn't need to display: block this

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +    position: static;
it shoulkd already be static

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +	outline: none;
Dont think this does anything

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +	cursor: pointer;
It should already go to the pointer because its an a tag

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.html
> +			</div>
Doing anything with this div?

2020-09-09 08:41 UTC, ashleycoles commented on portfolio.css
> +	content: 'Project ' counter(projects);
Nice!!

2020-09-09 11:20 UTC, cattre commented on portfolio.css
> +    margin-top: 0px;
Ah, not sure which lines these are on now - could you give me the class name? Might have changed some of them in the latest version...

2020-09-09 11:24 UTC, cattre commented on portfolio.css
> +	outline: none;
As with a previous comment, I'm not sure which element this is now (and it may have been updated). Please check with the next version.

2020-09-09 11:26 UTC, cattre commented on portfolio.html
> +			</div>
Yes - all in CSS

2020-09-10 13:12 UTC, ashleycoles commented on portfolio.css
> +	position: absolute;
I don't think this absolute needs to be here either

2020-09-10 13:14 UTC, ashleycoles commented on portfolio.css
> +		". c .";
Really nice use of grid, well done!

2020-09-10 13:15 UTC, ashleycoles commented on portfolio.css
> +	margin-top: 0;
I believe this div should already have a default top margin of 0, shouldn't need this line

2020-09-10 13:17 UTC, ashleycoles commented on portfolio.css
> +	margin-right: auto;
I don't think you need the left/right auto margin for this, the subtitle or the quote. Because you have text-align centre it should already be centred up.

2020-09-10 13:17 UTC, ashleycoles commented on portfolio.css
> +	color: white;
Replace with hex code

2020-09-10 13:19 UTC, ashleycoles commented on portfolio.css
> +	padding-bottom: 10px;
(Suggestion) These rules can be combined into a single one like so:

padding: 10px 30%;

10px top and bottom, 30% left and right

2020-09-10 13:26 UTC, ashleycoles commented on portfolio.html
> +			<div class='carousel'>
This is a very cool way of creating a JS-less slider. 

One thing I would say is that it won't work as well as one built using JavaScript, you'll probably find it doesn't work amazingly in weird browsers/mobile, but having said that we don't know any JS yet so I'm very happy to let it slide. Just something to be aware of for the future, might be worth coming back to it once you have some JS under your belt!

2020-09-10 13:28 UTC, ashleycoles commented on portfolio.css
> +	width: 100vw;
Avoid using VW like the plague, it's like % only worse. Switch for %

2020-09-10 13:28 UTC, ashleycoles commented on portfolio.css
> +	color: white;
Switch to hex

2020-09-10 13:29 UTC, ashleycoles commented on portfolio.css
> +	background-color: RGB(53,54,58);
I don't mind if you go for RGB or HEX, just make every colour code the same format (unless you needed to use alpha in which case it's ok to mix HEX with RGBA).

2020-09-10 13:29 UTC, ashleycoles commented on portfolio.css
> +	overflow-y: auto;
Shoulkdn't need the overflow-y here, think it's the default

2020-09-10 13:31 UTC, ashleycoles commented on portfolio.css
> +	height: 95%;
Does this height do anything?

2020-09-10 13:31 UTC, ashleycoles commented on portfolio.css
> +	background-color: RGB(53,54,58);
consistent colour formats please

2020-09-10 13:32 UTC, ashleycoles commented on portfolio.css
> +    height: 24.75vw;
Would suggest using % or px for this, setting a height based on a width can end up with weird results.

2020-09-10 13:33 UTC, ashleycoles commented on portfolio.css
> +	float: left;
Because the parent is flex there's no need to float

2020-09-10 13:34 UTC, ashleycoles commented on portfolio.html
> +			<div class='aboutimages'>
I'd say the same thing here about these images, this is something that would traditionally be done in JS (and would probs work a bit better), so might be worth bearing in mind for the future.

2020-09-10 13:41 UTC, ashleycoles commented on projects.css
> +.projectrow:nth-child(even) {
great use of nth-child

2020-09-10 13:42 UTC, ashleycoles commented on portfolio.html
> +		<div id='base'></div>
What's this doing here? Does it not work by linking to contact?

2020-09-10 14:06 UTC, cattre commented on portfolio.html
> +		<div id='base'></div>
Good point - it was causing me issues (scrolled too far up) which is why I added it, but seems OK now so have removed.

2020-09-10 15:22 UTC, ashleycoles requested changes

2020-09-10 15:22 UTC, ashleycoles commented on portfolio.css
> +	width: 100vw;
I have no idea why, but having the width set to 100vw means I get a little gap under your menu where the video shows. Setting it to 97 seems to fix it 😅

2020-09-10 15:24 UTC, cattre commented on portfolio.css
> +    height: 24.75vw;
Doesn't seem to want to work with %, and px is too rigid for responsiveness. Will take the risk for now...

2020-09-10 15:47 UTC, ashleycoles approved these changes

2020-09-10 15:49 UTC, merged